const text = {
  en: {
    chooseCountry: 'Choose country',
    cafes: 'Restaurants',
    belowCafesText: 'All available restaurants',
    favorites: 'Favorites',
    belowFavoritesText: 'Your favorite restaurants',
    search: 'Search',
    searchForShop: 'Search for restaurant',
    today: 'Today',
    opened: 'Opened',
    closed: 'Closed',
    somethingWentWrong: 'Something went wrong, check your internet connection',
    loading: 'Loading...',
    noShops: 'No restaurants found',
    noLocations: 'No locations found',
    noProducts: 'No products found',
    noFavorites: 'No favorite restaurants found',
    noUsers: 'No users found',
    noCafesMatchYourSearch: 'No restaurants match your search',
    noLocationsMatchYourSearch: 'No locations match your search',
    noMealsMatchYourSearch: 'No products match your search',
    noTimeZonesMatchYourSearch: 'No time zones match your search',
    noCurrenciesMatchYourSearch: 'No currencies match your search',
    noCountriesMatchYourSearch: 'No countries match your search',
    noLanguagesMatchYourSearch: 'No languages match your search',
    noUsersMatchYourSearch: 'No users match your search',
    add: 'Add',
    required: 'Required',
    continueShopping: 'Continue shopping',
    goToCart: 'Go to shopping cart',
    selectRequiredOptions: 'Select all required options!',
    ok: 'Ok',
    confirm: 'Confirm',
    cancel: 'Cancel',
    emptyCart: 'You have order from another restaurant in your shopping cart. Do you want to empty it?',
    itemAddedSuccessfully: 'Items added successfully!',
    cartIsEmpty: 'Shopping cart is empty. Start adding some items!',
    chooseDelivery: 'Choose delivery method',
    delivery: 'Delivery',
    takeAway: 'Take away',
    inPlace: 'Eat in',
    totalPrice: 'Total price:',
    buy: 'Buy',
    areYouSureDeleteItemFromCart: 'Are you sure you want to delete this product?',
    areYouSureDeleteItemFromProducts: 'Are you sure you want to delete this product?',
    areYouSureDeleteUser: 'Are you sure you want to delete this user',
    enterDeliveryDetails: 'Add your contact info',
    phoneNumber: 'Phone number',
    address: 'Address',
    doorCode: 'Door code',
    name: 'Name',
    enterAllRequiredFields: 'Enter all required fields',
    somethingWentWrongWhileSendingOrder: 'Something went wrong while sending order, check your internet connection',
    yourOderReadySoon: 'Your order will be ready soon!',
    settings: 'Settings',
    businessAccount: 'Business Account',
    businessAccountSettings: 'Business account settings',
    goToBusinessSettings: 'Sign in or register new account',
    signinSignupSettings: 'Sign in, Sign up, Settings...',
    signin: 'Sign in',
    signup: 'Sign up',
    signout: 'Sign out',
    businessName: 'Business name',
    email: 'E-mail',
    password: 'Password',
    confirmPassword: 'Confirm password',
    createNewAccount: 'Create new account',
    country: 'Country',
    emptyInputCountry: 'Input field country can not be empty',
    invalidInputCountry: 'You entered invalid country',
    emptyInputBusinessName: 'Input field business name can not be empty',
    invalidInputBusinessName: 'You entered invalid business name',
    emptyInputEmail: 'Input field e-mail can not be empty',
    invalidInputEmail: 'You entered invalid e-mail',
    emptyInputPassword: 'Input field password can not be empty',
    shortInputPassword: 'Password is to short',
    emptyInputConfirmPassword: 'Input field confirm password can not be empty',
    invalidOldPassword: 'You entered invalid old password',
    emptyInputNewPassword: 'Input field new password can not be empty',
    shortInputNewPassword: 'New password is to short',
    emptyInputConfirmNewPassword: 'Input field confirm new password can not be empty',
    emptyInputCity: 'Input field city can not be empty',
    emptyInputAddress: 'Input field address can not be empty',
    emptyInputPhoneNumber: 'Input field phone number can not be empty',
    invalidInputPhoneNumber: 'You entered invalid phone number',
    invaliTimeFormatMonday: 'Monday: invalid time format',
    invaliTimeFormatTuesday: 'Tuesday: invalid time format',
    invaliTimeFormatWednesday: 'Wednesday: invalid time format',
    invaliTimeFormatThursday: 'Thursday: invalid time format',
    invaliTimeFormatFriday: 'Friday: invalid time format',
    invaliTimeFormatSaturday: 'Saturday: invalid time format',
    invaliTimeFormatSunday: 'Sunday: invalid time format',
    somethingWentWrongAndTryLater: 'Something went wrong, check your internet connection and try later',
    passwordsAreNotEqual: 'Input fields confirm password and password are not equal',
    newPasswordsAreNotEqual: 'Input fields confirm new password and new password are not equal',
    myShop: 'Business',
    manageMyShop: 'Manage your business',
    invalidCredentials: 'Invalid credentials',
    description: 'Description',
    title: 'Title',
    manageLocations: 'Manage locations',
    manageProducts: 'Manage products',
    manageOrders: 'Manage orders',
    edit: 'Edit',
    editBusinessInfo: 'Edit business info',
    permissionDenied: 'You have no permission for adding or editing data',
    category: 'Category',
    price: 'Price',
    addNewProduct: 'Add new product',
    emptyInputCategory: 'Input field category can not be empty',
    emptyInputTitle: 'Input field title can not be empty',
    emptyInputPrice: 'Input field price can not be empty',
    invalidInputPrice: 'You entered invalid price',
    emptyInputDeliveryPrice: 'Input field delivery price can not be empty',
    invalidInputDeliveryPrice: 'You entered invalid delivery price',
    currency: 'Currency',
    emptyInputCurrency: 'Input field currency can not be empty',
    emailExists: 'User with this email already exists',
    addOption: 'Add option',
    skip: 'Skip',
    save: 'Save',
    multiple: 'Multiple',
    option: 'Option',
    additionalPrice: 'Additional price',
    enterTitleAndOption: 'Pleas enter title and at least one option',
    invalidPriceFormat: 'Invalid price format',
    areYouSureDeleteItem: 'Are you sure you want to delete this item?',
    invalidIOptionsFormat: 'Invalid options format',
    somethingWentWrongWhileLoadingDetails: 'Something went wrong while loading product options, check your internet connection and try later',
    editProduct: 'Edit product',
    city: 'City',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    addNewLocation: 'Add new location',
    editLocation: 'Edit location',
    workingHours: 'Working time',
    deliveryMethods: 'Delivery methods',
    chooseDeliveryMethods: 'Choose at least one delivery method',
    showDetails: 'Show details',

    // ### order status messages
    preparingMainMessage: 'Order is not yet ready for pick-up',
    preparingMainMessageDelivery: 'Order is not yet ready for delivery',

    preparingSecondaryMessage: 'You may follow the progress of your order on this screen. We will let you know when the products are ready for pick-up.',
    preparingSecondaryMessageDelivery: 'You may follow the progress of your order on this screen. We will let you know when the products are on the way.',

    readyMainMessage: 'Order ready for pick-up',
    readyMainMessageDelivery: 'Order on the way',

    readySecondaryMessage: 'Collect your order from pick-up point using the code.',
    readySecondaryMessageDelivery: 'Collect your order from courier using the code.',

    closedMainMessage: 'Thank you for your order',
    closedMainMessageDelivery: 'Thank you for your order',

    closedSecondaryMessage: 'Your order has been delivered.',
    closedSecondaryMessageDelivery: 'Your order has been delivered.',
    // #################

    somethingWentWrongWhileUpdatingOrderStatus: 'Something went wrong while updating order status, check your internet connection',
    somethingWentWrongWhileUpdatingOrders: 'Something went wrong while updating orders, check your internet connection',
    searchByOrderNumber: 'Search by order number',
    noOrders: 'No orders found',
    noOrdersMatchYourSearch: 'No orders match your search',
    order: 'Order',
    status: 'Status',
    sendTime: 'Send time',
    changeStatus: 'Change status',
    changeStatusTo: 'Change status to',
    preparing: 'Preparing',
    ready: 'Ready',
    closed: 'Closed',
    filters: 'Filters',
    orderDoNotExist: 'Order does not exist or where been deleted',
    productDoNotExist: 'Product does not exist or where been deleted',
    locationDoNotExist: 'Location does not exist or where been deleted',
    someOfLocationDoNotExist: 'Changes are not saved, some of locations do not exist or where been deleted',
    deliveryMethod: 'Delivery method',
    where: 'Where',
    who: 'Who',
    history: 'History',
    seeYourHistory: 'Your last orders',
    changePassword: 'Change password',
    changeEmail: 'Change e-mail',
    oldPassword: 'Old password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    productDoNotExist: 'Product does not exist or where been deleted',
    imageSizeIsToBig: 'Image size is to big. Maximum size is',
    mb: 'MB',
    supportedImageTypes: 'Wrong image type. Supported image types: jpg, jpeg and png.',
    deliveryPrice: 'Delivery price',
    noOrdersInHistory: 'No orders found',
    noOrdersInHistoryMatchYourSearch: 'No orders match your search',
    orderWillBeReady: 'Order will be ready after about',
    emptyInputTime: 'Input field time can not be empty',
    invalidInputTime: 'You entered invalid time',
    passwordChangedSuccessfully: 'Password changed successfully',
    emailChangedSuccessfully: 'E-mail changed successfully',
    accountDeleteddSuccessfully: 'Account deleted successfully',
    changeEmail: 'Change e-mail',
    deleteBusinessAccount: 'Delete business account',
    delete: 'Delete',
    typeBusinessAccount: 'Please type your business name to confirm',
    invalidBusinessAcccountToDelete: 'You entered invalid business name, enter your business name to confirm',
    loggedAs: 'Signed in as',
    admin: 'admin',
    manager: 'manager',
    areYourSureSignout: 'Are you sure you want to sign out?',
    manageNotifications: 'Manage notifications',
    chooseFromWichLocationsNotifications: 'Choose from wich locations you want to get notifications about new orders.',
    chooseFromWichLocationsOrders: 'Choose in wich location you want to manage orders.',
    manageUsers: 'Manage users',
    createUserPermissionOrderManaging: 'Add new users. New users will have permission only for managing orders.',
    timeZone: 'Time zone',
    addUser: 'Add new user',
    languageToChoose: 'Language you will use while using application',
    countryToChoose: 'Country where you will use application',
    forgotPassword: 'Forgot password?',
    resetPassword: 'Reset password',
    resetYourPassword: 'Reset your password',
    lostYourPasswordText: 'Lost your password? Please enter your email address. You will receive a new password via email. Login with new password and change it.',
    userWithEmailDoNotExist: 'User with this email does not exist',
    newPasswordSendedSuccessfully: 'New password sended successfully',
    restaurantInThisLocationIsClosed: 'Restaurant in this location is closed',
    restaurantWithThisLocationDoNotExist: 'Restaurant with such location does not exist',
    hh: 'hh',
    mm: 'mm',
  },
  ru: {
    chooseCountry: 'Выберите страну',
    cafes: 'Рестораны',
    belowCafesText: 'Все доступные рестораны',
    favorites: 'Избранное',
    belowFavoritesText: 'Избранные рестораны',
    search: 'Поиск',
    searchForShop: 'Поиск ресторана',
    today: 'Сегодня',
    opened: 'Открыто',
    closed: 'Закрыто',
    somethingWentWrong: 'Что-то пошло не так, проверьте подключение к интернету',
    loading: 'Загрузка...',
    noShops: 'Ресторанов не найдено',
    noLocations: 'Местоположений не найдено',
    noProducts: 'Продуктов не найдено',
    noFavorites: 'Избранных ресторанов не найдено',
    noCafesMatchYourSearch: 'Нет ресторанов, соответствующих вашему запросу',
    noUsers: 'Пользователей не найдено',
    noLocationsMatchYourSearch: 'Нет местоположений, соответствующих вашему запросу',
    noMealsMatchYourSearch: 'Нет продуктов, соответствующий вашему запросу',
    noTimeZonesMatchYourSearch: 'Нет временных поясов, соответствующих вашему запросу',
    noCurrenciesMatchYourSearch: 'Нет валют, соответствующих вашему запросу',
    noCountriesMatchYourSearch: 'Нет стран, соответствующих вашему запросу',
    noLanguagesMatchYourSearch: 'Нет языков, соответствующих вашему запросу',
    noUsersMatchYourSearch: 'Нет пользователей, соответствующих вашему запросу',
    add: 'Добавить',
    required: 'Обязательно',
    continueShopping: 'Продолжить покупки',
    goToCart: 'Перейти в корзину',
    selectRequiredOptions: 'Выберите все обязательные параметры!',
    ok: 'Ok',
    confirm: 'Подтвердить',
    cancel: 'Отменить',
    emptyCart: 'У вас есть заказ из другого ресторана в корзине. Вы хотите ее опустошить?',
    itemAddedSuccessfully: 'Товары успешно добавлены!',
    cartIsEmpty: 'Корзина пуста. Начните добавлять товары!',
    chooseDelivery: 'Выберите способ доставки',
    delivery: 'Доставка',
    takeAway: 'На вынос',
    inPlace: 'На месте',
    totalPrice: 'Итоговая цена:',
    buy: 'Купить',
    areYouSureDeleteItemFromCart: 'Вы уверены, что хотите удалить этот продукт?',
    areYouSureDeleteItemFromProducts: 'Вы уверены, что хотите удалить этот продукт?',
    areYouSureDeleteUser: 'Вы уверены, что хотите удалить этого пользователя',
    enterDeliveryDetails: 'Добавьте свою контактную информацию',
    phoneNumber: 'Номер телефона',
    address: 'Адрес',
    doorCode: 'Код двери',
    name: 'Имя',
    enterAllRequiredFields: 'Введите все обязательные поля',
    somethingWentWrongWhileSendingOrder: 'Что-то пошло не так при отправке заказа, проверьте интернет-соединение',
    yourOderReadySoon: 'Ваш заказ будет готов в ближайшее время!',
    settings: 'Настройки',
    businessAccount: 'Бизнес Аккаунт',
    businessAccountSettings: 'Настройки бизнес аккаунта',
    goToBusinessSettings: 'Войдите или зарегистрируйте новый аккаунта',
    signinSignupSettings: 'Войти, Зарегистрироваться, Настройки...',
    signin: 'Вход',
    signup: 'Регистрация',
    signout: 'Выйти',
    businessName: 'Название бизнеса',
    email: 'Электронная почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердить пароль',
    createNewAccount: 'Создать новый аккаунт',
    country: 'Страна',
    emptyInputCountry: 'Поле ввода страна не может быть пустым',
    invalidInputCountry: 'Вы ввели недействительную страну',
    emptyInputBusinessName: 'Поле ввода название бизнеса не может быть пустым',
    invalidInputBusinessName: 'Вы ввели недействительное название бизнеса',
    emptyInputEmail: 'Поле ввода электронная почта не может быть пустым',
    invalidInputEmail: 'Вы ввели недействительный адрес электронной почты',
    emptyInputPassword: 'Поле ввода пароль не может быть пустым',
    shortInputPassword: 'Пароль слишком короткий',
    emptyInputConfirmPassword: 'Поле ввода подтвердить пароль не может быть пустым',
    invalidOldPassword: 'Вы ввели неверный старый пароль',
    emptyInputNewPassword: 'Поле ввода новый пароль не может быть пустым',
    shortInputNewPassword: 'Новый пароль слишком короткий',
    emptyInputConfirmNewPassword: 'Поле ввода подтвердить новый пароль не может быть пустым',
    emptyInputCity: 'Поле ввода город не может быть пустым',
    emptyInputAddress: 'Поле ввода адрес не может быть пустым',
    emptyInputPhoneNumber: 'Поле ввода номер телефона не может быть пустым',
    invalidInputPhoneNumber: 'Вы ввели недействительный номер телефона',
    invaliTimeFormatMonday: 'Понедельник: недействительный формат времени',
    invaliTimeFormatTuesday: 'Вторник: недействительный формат времени',
    invaliTimeFormatWednesday: 'Среда: недействительный формат времени',
    invaliTimeFormatThursday: 'Четверг: недействительный формат времени',
    invaliTimeFormatFriday: 'Пятница: недействительный формат времени',
    invaliTimeFormatSaturday: 'Суббота: недействительный формат времени',
    invaliTimeFormatSunday: 'Воскресенье: недействительный формат времени',
    somethingWentWrongAndTryLater: 'Что-то пошло не так, проверьте подключение к интернету и повторите попытку позже.',
    passwordsAreNotEqual: 'Поля ввода подтвердить пароль и пароль не равны',
    newPasswordsAreNotEqual: 'Поля ввода подтвердить новый пароль и новый пароль не равны',
    myShop: 'Бизнес',
    manageMyShop: 'Управление своим бизнесом',
    invalidCredentials: 'Недействительные данные учетной записи',
    description: 'Описание',
    title: 'Название',
    manageLocations: 'Управление местоположениями',
    manageProducts: 'Управление продуктами',
    manageOrders: 'Управление заказами',
    edit: 'Редактировать',
    editBusinessInfo: 'Изменить информацию о бизнесе',
    permissionDenied: 'У вас нет разрешения на добавление или редактирование данных',
    category: 'Категория',
    price: 'Цена',
    addNewProduct: 'Добавить новый продукт',
    emptyInputCategory: 'Поле ввода категория не может быть пустой',
    emptyInputTitle: 'Поле ввода название не может быть пустым',
    emptyInputPrice: 'Поле ввода цена не может быть пустым',
    invalidInputPrice: 'Вы ввели недействительную цену',
    emptyInputDeliveryPrice: 'Поле ввода цена доставки не может быть пустым',
    invalidInputDeliveryPrice: 'Вы ввели недействительную цену доставки',
    currency: 'Валюта',
    emptyInputCurrency: 'Поле ввода валюта не может быть пустым',
    emailExists: 'Пользователь с таким адресом электронной почты уже существует',
    addOption: 'Добавить опцию',
    skip: 'Пропустить',
    save: 'Сохранить',
    multiple: 'Несколько',
    option: 'Опция',
    additionalPrice: 'Дополнительная цена',
    enterTitleAndOption: 'Пожалуйста, введите название и хотя бы одну опцию',
    invalidPriceFormat: 'Неверный формат цены',
    areYouSureDeleteItem: 'Вы уверены, что хотите удалить этот элемент?',
    invalidIOptionsFormat: 'Неверный формат опций',
    somethingWentWrongWhileLoadingDetails: 'Что-то пошло не так при загрузке опций продукта, проверьте подключение к Интернету и повторите попытку позже',
    editProduct: 'Редактировать продукт',
    city: 'Город',
    monday: 'Понедельник',
    tuesday: 'Вторник',
    wednesday: 'Среда',
    thursday: 'Четверг',
    friday: 'Пятница',
    saturday: 'Суббота',
    sunday: 'Воскресенье',
    addNewLocation: 'Добавить новое местоположение',
    editLocation: 'Редактировать местоположение',
    workingHours: 'Рабочее время',
    deliveryMethods: 'Способы доставки',
    chooseDeliveryMethods: 'Выберите хотя бы один способ доставки',
    showDetails: 'Показать детали',

    // ### order status messages
    preparingMainMessage: 'Заказ еще не готов к выдаче',
    preparingMainMessageDelivery: 'Заказ еще не готов к доставке',

    preparingSecondaryMessage: 'Вы можете следить за ходом выполнения вашего заказа на этом экране. Мы сообщим вам, когда товары будут готовы к выдаче.',
    preparingSecondaryMessageDelivery: 'Вы можете следить за ходом выполнения вашего заказа на этом экране. Мы сообщим вам, когда товары будут в пути.',

    readyMainMessage: 'Заказ готов к выдаче',
    readyMainMessageDelivery: 'Заказ в пути',

    readySecondaryMessage: 'Заберите свой заказ используя код.',
    readySecondaryMessageDelivery: 'Заберите свой заказ у курьера, используя код.',

    closedMainMessage: 'Спасибо за ваш заказ',
    closedMainMessageDelivery: 'Спасибо за ваш заказ',

    closedSecondaryMessage: 'Ваш заказ доставлен.',
    closedSecondaryMessageDelivery: 'Ваш заказ доставлен.',
    // #################

    somethingWentWrongWhileUpdatingOrderStatus: 'Что-то пошло не так при обновлении статуса заказа, проверьте подключение к интернету',
    somethingWentWrongWhileUpdatingOrders: 'Что-то пошло не так при обновлении заказов, проверьте подключение к интернету',
    searchByOrderNumber: 'Поиск по номеру заказа',
    noOrders: 'Заказов не найдено',
    noOrdersMatchYourSearch: 'Нет заказов, соответствующих вашему запросу',
    order: 'Заказ',
    status: 'Статус',
    sendTime: 'Отправить время',
    changeStatus: 'Изменить статус',
    changeStatusTo: 'Изменить статус на',
    preparing: 'Подготовка',
    ready: 'Готов',
    closed: 'Закрыто',
    filters: 'Фильтры',
    orderDoNotExist: 'Заказ не существует или был удален',
    productDoNotExist: 'Продукт не существует или был удален',
    locationDoNotExist: 'Местоположение не существует или было удалено',
    someOfLocationDoNotExist: 'Изменения не сохранены, некоторые местоположения не существуют или были удалены',
    deliveryMethod: 'Способ доставки',
    where: 'Где',
    who: 'Кто',
    history: 'История',
    seeYourHistory: 'Ваши последние заказы',
    changePassword: 'Изменить пароль',
    changeEmail: 'Изменить электронную почту',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    confirmNewPassword: 'Подтвердить новый пароль',
    productDoNotExist: 'Продукт не существует или был удален',
    imageSizeIsToBig: 'Размер изображения слишком большой. Максимальный размер',
    mb: 'MB',
    supportedImageTypes: 'Недействительный тип изображения. Поддерживаемые типы изображений: jpg, jpeg и png.',
    deliveryPrice: 'Цена доставки',
    noOrdersInHistory: 'Заказов не найдено',
    noOrdersInHistoryMatchYourSearch: 'Нет заказов, соответствующих вашему запросу',
    orderWillBeReady: 'Заказ будет готов примерно через',
    emptyInputTime: 'Поле ввода времени не может быть пустым',
    invalidInputTime: 'Вы ввели недействительное время',
    passwordChangedSuccessfully: 'Пароль успешно изменен',
    emailChangedSuccessfully: 'Электронная почта успешно изменена',
    accountDeleteddSuccessfully: 'Аккаунт успешно удален',
    changeEmail: 'Изменить электроннюу почту',
    deleteBusinessAccount: 'Удалить бизнес аккаунт',
    delete: 'Удалить',
    typeBusinessAccount: 'Пожалуйста, введите название вашего бизнеса для подтверждения',
    invalidBusinessAcccountToDelete: 'Вы ввели неправильное название бизнеса. Введите название своего бизнеса для подтверждения.',
    loggedAs: 'Вы вошли как',
    admin: 'админ',
    manager: 'менеджер',
    areYourSureSignout: 'Вы уверены, что хотите выйти?',
    manageNotifications: 'Управление уведомлениями',
    chooseFromWichLocationsNotifications: 'Выберите, из каких местоположений вы хотите получать уведомления о новых заказах.',
    chooseFromWichLocationsOrders: 'Выберите, в каком местоположении вы хотите управлять заказами.',
    manageUsers: 'Управление пользователями',
    createUserPermissionOrderManaging: 'Добавьте новых пользователей. Новые пользователи будут иметь разрешение только на управление заказами.',
    timeZone: 'Часовой пояс',
    addUser: 'Добавить нового пользователя',
    languageToChoose: 'Язык, который вы будете использовать в приложении',
    countryToChoose: 'Страна, в которой вы будете использовать приложение',
    forgotPassword: 'Забыли пароль?',
    resetPassword: 'Восстановить пароль',
    resetYourPassword: 'Восстановление пароля',
    lostYourPasswordText: 'Забыли пароль? Пожалуйста, введите ваш адрес электронной почты. Вы получите новый пароль по электронной почте. Войдите с новым паролем и измените его.',
    userWithEmailDoNotExist: 'Пользователь с таким адресом электронной почты не существует',
    newPasswordSendedSuccessfully: 'Новый пароль успешно отправлен',
    restaurantInThisLocationIsClosed: 'Ресторан в этом местоположении закрыт',
    restaurantWithThisLocationDoNotExist: 'Ресторан с таким местоположением не существует',
    hh: 'чч',
    mm: 'мм',
  },
  lv: {
    chooseCountry: 'Izvēlieties valsti',
    cafes: 'Restorāni',
    belowCafesText: 'Visi pieejamie restorāni',
    favorites: 'Favorīti',
    belowFavoritesText: 'Iecienītākie restorāni',
    search: 'Meklēt',
    searchForShop: 'Restorānu meklēšana',
    today: 'Šodien',
    opened: 'Atvērts',
    closed: 'Slēgts',
    somethingWentWrong: 'Radās problēma, pārbaudiet interneta savienojumu',
    loading: 'Notiek ielāde...',
    noShops: 'Restorāni nav atrasti',
    noLocations: 'Atrašanās vietas nav atrastas',
    noProducts: 'Produkti nav atrasti',
    noFavorites: 'Favorītos restorāni nav atrasti',
    noCafesMatchYourSearch: 'Meklēšanai neatbilst neviens restorāns',
    noUsers: 'Lietotāji nav atrasti',
    noLocationsMatchYourSearch: 'Meklēšanai neatbilst neviena atrašanas vieta',
    noMealsMatchYourSearch: 'Meklēšanai neatbilst neviens produkts',
    noTimeZonesMatchYourSearch: 'Meklēšanai neatbilst neviena laika zona',
    noCurrenciesMatchYourSearch: 'Meklēšanai neatbilst neviena valūta',
    noCountriesMatchYourSearch: 'Meklēšanai neatbilst neviena valsts',
    noLanguagesMatchYourSearch: 'Meklēšanai neatbilst neviena valoda',
    noUsersMatchYourSearch: 'Meklēšanai neatbilst neviens lietotajs',
    add: 'Pievienot',
    required: 'Obligāti',
    continueShopping: 'Turpināt iepirkties',
    goToCart: 'Doties uz iepirkumu grozu',
    selectRequiredOptions: 'Izvēlieties visas obligātās opcijas!',
    ok: 'Ok',
    confirm: 'Apstiprināt',
    cancel: 'Atcelt',
    emptyCart: 'Jūsu iepirkumu grozā ir pasūtījums no cita restorāna. Vai vēlaties to iztukšot?',
    itemAddedSuccessfully: 'Produkti ir veiksmīgi pievienoti!',
    cartIsEmpty: 'Iepirkumu grozs ir tukšs. Sāciet pievienot produktus!',
    chooseDelivery: 'Izvēlieties piegādes veidu',
    delivery: 'Piegāde',
    takeAway: 'Līdzņemšana',
    inPlace: 'Uz vietas',
    totalPrice: 'Kopējā cena:',
    buy: 'Pirkt',
    areYouSureDeleteItemFromCart: 'Vai tiešām vēlaties dzēst šo produktu?',
    areYouSureDeleteItemFromProducts: 'Vai tiešām vēlaties dzēst šo produktu?',
    areYouSureDeleteUser: 'Vai tiešām vēlaties dzēst šo lietotāju',
    enterDeliveryDetails: 'Pievienojiet savu kontaktinformāciju',
    phoneNumber: 'Telefona numurs',
    address: 'Adrese',
    doorCode: 'Durvju kods',
    name: 'Vārds',
    enterAllRequiredFields: 'Ievadiet visus obligātos laukus',
    somethingWentWrongWhileSendingOrder: 'Pasūtījuma nosūtīšanas laikā radās problēma, pārbaudiet interneta savienojumu',
    yourOderReadySoon: 'Jūsu pasūtījums drīz būs gatavs!',
    settings: 'Iestatījumi',
    businessAccount: 'Biznesa konts',
    businessAccountSettings: 'Biznesa konta iestatījumi',
    goToBusinessSettings: 'Pieslēgties vai reģistrēt jaunu kontu',
    signinSignupSettings: 'Pieslēgties, reģistrēties, iestatījumi...',
    signin: 'Pieslēgties',
    signup: 'Reģistrēties',
    signout: 'Izrakstīties',
    businessName: 'Biznesa nosaukums',
    email: 'E-pasts',
    password: 'Parole',
    confirmPassword: 'Apstiprināt paroli',
    createNewAccount: 'Izveidot jaunu kontu',
    country: 'Valsts',
    emptyInputCountry: 'Ievades lauks valsts nevar būt tukšs',
    invalidInputCountry: 'Jūs ievadījāt nederīgu valsti',
    emptyInputBusinessName: 'Ievades lauks biznesa nosaukums nevar būt tukšs',
    invalidInputBusinessName: 'Jūs ievadījāt nederīgu biznesa nosaukumu',
    emptyInputEmail: 'Ievades lauks e-pasts nevar būt tukšs',
    invalidInputEmail: 'Jūs ievadījāt nederīgu e-pastu',
    emptyInputPassword: 'Ievades lauks parole nevar būt tukšs',
    shortInputPassword: 'Parole ir par īsu',
    emptyInputConfirmPassword: 'Ievades lauks apstiprināt paroli nevar būt tukšs',
    invalidOldPassword: 'Jūs ievadījāt nepareizu veco paroli',
    emptyInputNewPassword: 'Ievades lauks jaunā parole nevar būt tukšs',
    shortInputNewPassword: 'Jaunā parole ir par īsu',
    emptyInputConfirmNewPassword: 'Ievades lauks apstiprināt jauno paroli nevar būt tukšs',
    emptyInputCity: 'Ievades lauks pilsēta nevar būt tukšs',
    emptyInputAddress: 'Ievades lauks adrese nevar būt tukšs',
    emptyInputPhoneNumber: 'Ievades lauks telefona numurs nevar būt tukšs',
    invalidInputPhoneNumber: 'Jūs ievadījāt nederīgu telefona numuru',
    invaliTimeFormatMonday: 'Pirmdiena: nederīgs laika formāts',
    invaliTimeFormatTuesday: 'Otrdiena: nederīgs laika formāts',
    invaliTimeFormatWednesday: 'Trešdiena: nederīgs laika formāts',
    invaliTimeFormatThursday: 'Ceturtdiena: nederīgs laika formāts',
    invaliTimeFormatFriday: 'Piektdiena: nederīgs laika formāts',
    invaliTimeFormatSaturday: 'Sestdiena: nederīgs laika formāts',
    invaliTimeFormatSunday: 'Svētdiena: nederīgs laika formāts',
    somethingWentWrongAndTryLater: 'Radās problēma, pārbaudiet interneta savienojumu un mēģiniet vēlāk',
    passwordsAreNotEqual: 'Ievades lauki apstiprināt paroli un parole nav vienādi',
    newPasswordsAreNotEqual: 'Ievades lauki apstiprināt jauno paroli un jaunā parole nav vienādi',
    myShop: 'Bizness',
    manageMyShop: 'Pārvaldīt savu biznesu',
    invalidCredentials: 'Nepareizs lietotājvārds un/vai parole',
    description: 'Apraksts',
    title: 'Nosaukums',
    manageLocations: 'Pārvaldīt atrašanas vietas',
    manageProducts: 'Pārvaldīt produktus',
    manageOrders: 'Pārvaldīt pasūtījumus',
    edit: 'Rediģēt',
    editBusinessInfo: 'Rediģēt biznesa informāciju',
    permissionDenied: 'Jums nav atļaujas datu pievienošanai vai rediģēšanai',
    category: 'Kategorija',
    price: 'Cena',
    addNewProduct: 'Pievienot jaunu produktu',
    emptyInputCategory: 'Ievades lauks kategorija nevar būt tukšs',
    emptyInputTitle: 'Ievades lauks nosaukums nevar būt tukšs',
    emptyInputPrice: 'Ievades lauks cena nevar būt tukšs',
    invalidInputPrice: 'Jūs ievadījāt nederīgu cenu',
    emptyInputDeliveryPrice: 'Ievades lauks piegādes cena nevar būt tukšs',
    invalidInputDeliveryPrice: 'Jūs ievadījāt nederīgu piegādes cenu',
    currency: 'Valūta',
    emptyInputCurrency: 'Ievades lauks valūta nevar būt tukšs',
    emailExists: 'Lietotājs ar šo e-pastu jau eksistē',
    addOption: 'Pievienot opciju',
    skip: 'Izlaist',
    save: 'Saglabāt',
    multiple: 'Vairākas',
    option: 'Opcija',
    additionalPrice: 'Papildu cena',
    enterTitleAndOption: 'Lūdzu, ievadiet nosaukumu un vismaz vienu opciju',
    invalidPriceFormat: 'Nederīgs cenas formāts',
    areYouSureDeleteItem: 'Vai esat pārliecināts, ka vēlaties izdzēst šo vienumu?',
    invalidIOptionsFormat: 'Nederīgs opciju formāts',
    somethingWentWrongWhileLoadingDetails: 'Produkta opciju ielādes laikā radās problēma, pārbaudiet interneta savienojumu un mēģiniet vēlāk',
    editProduct: 'Rediģēt produktu',
    city: 'Pilsēta',
    monday: 'Pirmdiena',
    tuesday: 'Otrdiena',
    wednesday: 'Trešdiena',
    thursday: 'Ceturtdiena',
    friday: 'Piektdiena',
    saturday: 'Sestdiena',
    sunday: 'Svētdiena',
    addNewLocation: 'Pievienot jaunu atrašanās vietu',
    editLocation: 'Rediģēt atrašanās vietu',
    workingHours: 'Darba laiks',
    deliveryMethods: 'Piegādes veidi',
    chooseDeliveryMethods: 'Izvēlieties vismaz vienu piegādes veidu',
    showDetails: 'Parādīt detaļas',

    // ### order status messages
    preparingMainMessage: 'Pasūtījums vēl nav gatavs izņemšanai',
    preparingMainMessageDelivery: 'Pasūtījums vēl nav gatavs piegādei',

    preparingSecondaryMessage: 'Šajā ekrānā jūs varat sekot pasūtījuma progresam. Mēs jums paziņosim, kad produkti būs gatavi izņemšanai.',
    preparingSecondaryMessageDelivery: 'Šajā ekrānā jūs varat sekot pasūtījuma progresam. Mēs jums paziņosim, kad produkti būs ceļā.',

    readyMainMessage: 'Pasūtījums gatavs izņemšanai',
    readyMainMessageDelivery: 'Pasūtījums ceļā',

    readySecondaryMessage: 'Paņemiet savu pasūtījumu, izmantojot kodu.',
    readySecondaryMessageDelivery: 'Paņemiet savu pasūtījumu no kurjera, izmantojot kodu.',

    closedMainMessage: 'Paldies par jūsu pasūtījumu',
    closedMainMessageDelivery: 'Paldies par jūsu pasūtījumu',

    closedSecondaryMessage: 'Jūsu pasūtījums ir piegādāts.',
    closedSecondaryMessageDelivery: 'Jūsu pasūtījums ir piegādāts.',
    // #################

    somethingWentWrongWhileUpdatingOrderStatus: 'Pasūtījuma statusa atjaunošanas laikā radās problēma, pārbaudiet interneta savienojumu',
    somethingWentWrongWhileUpdatingOrders: 'Pasūtījumu atjaunošanas laikā radās problēma, pārbaudiet interneta savienojumu',
    searchByOrderNumber: 'Meklēt pēc pasūtījuma numura',
    noOrders: 'Pasūtījumi nav atrasti',
    noOrdersMatchYourSearch: 'Meklēšanai neatbilst neviens pasūtījums',
    order: 'Pasūtījums',
    status: 'Statuss',
    sendTime: 'Nosūtīt laiku',
    changeStatus: 'Mainīt statusu',
    changeStatusTo: 'Mainīt statusu uz',
    preparing: 'Sagatavošana',
    ready: 'Gatavs',
    closed: 'Slēgts',
    filters: 'Filtri',
    orderDoNotExist: 'Pasūtījums neeksistē vai tika izdzēsts',
    productDoNotExist: 'Produkts neeksistē vai tika izdzēsts',
    locationDoNotExist: 'Atrašanas vieta neeksistē vai tika izdzēsta',
    someOfLocationDoNotExist: 'Izmaiņas netika saglabātas, dažas atrašanas vietas neeksistē vai tika izdzēstas',
    deliveryMethod: 'Piegādes veids',
    where: 'Kur',
    who: 'Kas',
    history: 'Vēsture',
    seeYourHistory: 'Jūsu pēdējie pasūtījumi',
    changePassword: 'Mainīt paroli',
    changeEmail: 'Mainīt e-pastu',
    oldPassword: 'Vecā parole',
    newPassword: 'Jaunā parole',
    confirmNewPassword: 'Apstiprināt jauno paroli',
    productDoNotExist: 'Produkts neeksistē vai tika izdzēsts',
    imageSizeIsToBig: 'Attēla izmērs ir pārāk liels. Maksimālais izmērs ir',
    mb: 'MB',
    supportedImageTypes: 'Nepareizs attēla veids. Atbalstītie attēlu veidi: jpg, jpeg and png.',
    deliveryPrice: 'Piegādes cena',
    noOrdersInHistory: 'Pasūtījumi nav atrasti',
    noOrdersInHistoryMatchYourSearch: 'Meklēšanai neatbilst neviens pasūtījums',
    orderWillBeReady: 'Pasūtījums būs gatavs pēc apmēram',
    emptyInputTime: 'Ievades lauks laiks nevar būt tukšs',
    invalidInputTime: 'Jūs ievadījāt nederīgu laiku',
    passwordChangedSuccessfully: 'Parole veiksmīgi izmainīta',
    emailChangedSuccessfully: 'E-pasts veiksmīgi izmainīts',
    accountDeleteddSuccessfully: 'Konts veiksmīgi izdzēsts',
    changeEmail: 'Mainīt e-pastu',
    deleteBusinessAccount: 'Dzēst biznesa kontu',
    delete: 'Dzēst',
    typeBusinessAccount: 'Lūdzu, ievadiet sava biznesa nosaukumu, lai apstiprinātu',
    invalidBusinessAcccountToDelete: 'Jūs ievadījāt nepareizu biznesa nosaukumu. Ievadiet sava biznesa nosaukumu, lai apstiprinātu',
    loggedAs: 'Jūs pieslēdzaties kā',
    admin: 'admin',
    manager: 'menedžeris',
    areYourSureSignout: 'Vai esat pārliecināts, ka vēlaties izrakstīties?',
    manageNotifications: 'Pārvaldīt paziņojumus',
    chooseFromWichLocationsNotifications: 'Izvēlieties atrašanas vietas no kurām vēlaties saņemt paziņojumus par jauniem pasūtījumiem.',
    chooseFromWichLocationsOrders: 'Izvēlieties, kurā  atrašanas vietā vēlaties pārvaldīt pasūtījumus.',
    manageUsers: 'Pārvaldīt lietotājus',
    createUserPermissionOrderManaging: 'Pievienojiet jaunus lietotājus. Jaunajiem lietotājiem būs atļauja tikai pārvaldīt pasūtījumus.',
    timeZone: 'Laika zona',
    addUser: 'Pievienot jaunu lietotāju',
    languageToChoose: 'Valoda, kuru izmantosiet aplikācijā',
    countryToChoose: 'Valsts, kurā izmantosiet aplikāciju',
    forgotPassword: 'Aizmirsāt paroli?',
    resetPassword: 'Atjaunot paroli',
    resetYourPassword: 'Atjaunot jūsu paroli',
    lostYourPasswordText: 'Pazaudējāt paroli? Lūdzu ievadiet savu e-pasta adresi. Jūs saņemsit jaunu paroli pa e-pastu. Pieslēdzieties ar jauno paroli un izmainiet to.',
    userWithEmailDoNotExist: 'Lietotājs ar šo e-pastu neeksistē',
    newPasswordSendedSuccessfully: 'Jaunā parole veiksmīgi nosūtīta',
    restaurantInThisLocationIsClosed: 'Restorāns šajā atrašanas vietā ir slēgts',
    restaurantWithThisLocationDoNotExist: 'Restorāns ar šādu atrašanās vietu neeksistē',
    hh: 'hh',
    mm: 'mm',
  },
};

// Countries
text.en.countries = {
  Afghanistan: 'Afghanistan',
  Albania: 'Albania',
  Algeria: 'Algeria',
  Andorra: 'Andorra',
  Angola: 'Angola',
  AntiguaAndBarbuda: 'Antigua and Barbuda',
  Argentina: 'Argentina',
  Armenia: 'Armenia',
  Aruba: 'Aruba',
  Australia: 'Australia',
  Austria: 'Austria',
  Azerbaijan: 'Azerbaijan',
  Bahamas: 'Bahamas',
  Bahrain: 'Bahrain',
  Bangladesh: 'Bangladesh',
  Barbados: 'Barbados',
  Belarus: 'Belarus',
  Belgium: 'Belgium',
  Belize: 'Belize',
  Benin: 'Benin',
  Bermuda: 'Bermuda',
  Bhutan: 'Bhutan',
  Bolivia: 'Bolivia',
  BosniaAndHerzegovina: 'Bosnia and Herzegovina',
  Botswana: 'Botswana',
  Brazil: 'Brazil',
  BritishVirginIslands: 'British Virgin Islands',
  Brunei: 'Brunei',
  Bulgaria: 'Bulgaria',
  BurkinaFaso: 'Burkina Faso',
  Burundi: 'Burundi',
  CaboVerde: 'Cabo Verde',
  Cambodia: 'Cambodia',
  Cameroon: 'Cameroon',
  Canada: 'Canada',
  CaymanIslands: 'Cayman Islands',
  CentralAfricanRepublic: 'Central African Republic',
  Chad: 'Chad',
  Chile: 'Chile',
  China: 'China',
  Colombia: 'Colombia',
  Comoros: 'Comoros',
  CongoBrazzaville: 'Congo-Brazzaville',
  CongoKinshasa: 'Congo-Kinshasa',
  CostaRica: 'Costa Rica',
  CoteDIvoire: 'Côte d’Ivoire',
  Croatia: 'Croatia',
  Cuba: 'Cuba',
  Curacao: 'Curaçao',
  Cyprus: 'Cyprus',
  Czechia: 'Czechia',
  Denmark: 'Denmark',
  FaroeIslands: 'Faroe Islands',
  Greenland: 'Greenland',
  Djibouti: 'Djibouti',
  Dominica: 'Dominica',
  DominicanRepublic: 'Dominican Republic',
  Ecuador: 'Ecuador',
  Egypt: 'Egypt',
  ElSalvador: 'El Salvador',
  EquatorialGuinea: 'Equatorial Guinea',
  Eritrea: 'Eritrea',
  Estonia: 'Estonia',
  Eswatini: 'Eswatini',
  Ethiopia: 'Ethiopia',
  Fiji: 'Fiji',
  Finland: 'Finland',
  AlandIslands: 'Åland Islands',
  France: 'France',
  FrenchGuiana: 'French Guiana',
  FrenchPolynesia: 'French Polynesia',
  Guadeloupe: 'Guadeloupe',
  Martinique: 'Martinique',
  Mayotte: 'Mayotte',
  NewCaledonia: 'New Caledonia',
  Reunion: 'Réunion',
  SaintBarthelemy: 'Saint Barthélemy',
  SaintMartin: 'Saint Martin',
  SaintPierreAndMiquelon: 'Saint Pierre and Miquelon',
  WallisAndFutuna: 'Wallis and Futuna',
  Gabon: 'Gabon',
  Gambia: 'Gambia',
  Georgia: 'Georgia',
  Germany: 'Germany',
  Ghana: 'Ghana',
  Gibraltar: 'Gibraltar',
  Greece: 'Greece',
  Grenada: 'Grenada',
  Guatemala: 'Guatemala',
  Guinea: 'Guinea',
  GuineaBissau: 'Guinea-Bissau',
  Guyana: 'Guyana',
  Haiti: 'Haiti',
  Honduras: 'Honduras',
  HongKong: 'Hong Kong',
  Hungary: 'Hungary',
  Iceland: 'Iceland',
  India: 'India',
  Indonesia: 'Indonesia',
  Iran: 'Iran',
  Iraq: 'Iraq',
  Ireland: 'Ireland',
  Israel: 'Israel',
  Italy: 'Italy',
  Jamaica: 'Jamaica',
  Japan: 'Japan',
  Jordan: 'Jordan',
  Kazakhstan: 'Kazakhstan',
  Kenya: 'Kenya',
  Kiribati: 'Kiribati',
  Kosovo: 'Kosovo',
  Kuwait: 'Kuwait',
  Kyrgyzstan: 'Kyrgyzstan',
  Laos: 'Laos',
  Latvia: 'Latvia',
  Lebanon: 'Lebanon',
  Lesotho: 'Lesotho',
  Liberia: 'Liberia',
  Libya: 'Libya',
  Liechtenstein: 'Liechtenstein',
  Lithuania: 'Lithuania',
  Luxembourg: 'Luxembourg',
  Madagascar: 'Madagascar',
  Malawi: 'Malawi',
  Malaysia: 'Malaysia',
  Maldives: 'Maldives',
  Mali: 'Mali',
  Malta: 'Malta',
  MarshallIslands: 'Marshall Islands',
  Mauritania: 'Mauritania',
  Mauritius: 'Mauritius',
  Mexico: 'Mexico',
  Micronesia: 'Micronesia',
  Moldova: 'Moldova',
  Monaco: 'Monaco',
  Mongolia: 'Mongolia',
  Montenegro: 'Montenegro',
  Morocco: 'Morocco',
  Mozambique: 'Mozambique',
  Namibia: 'Namibia',
  Nauru: 'Nauru',
  Nepal: 'Nepal',
  Netherlands: 'Netherlands',
  NewZealand: 'New Zealand',
  Nicaragua: 'Nicaragua',
  Niger: 'Niger',
  Nigeria: 'Nigeria',
  NorthMacedonia: 'North Macedonia',
  Norway: 'Norway',
  SvalbardAndJanMayen: 'Svalbard and Jan Mayen',
  Oman: 'Oman',
  Pakistan: 'Pakistan',
  Palau: 'Palau',
  Panama: 'Panama',
  PapuaNewGuinea: 'Papua New Guinea',
  Paraguay: 'Paraguay',
  Peru: 'Peru',
  Philippines: 'Philippines',
  Poland: 'Poland',
  Portugal: 'Portugal',
  Qatar: 'Qatar',
  Romania: 'Romania',
  Russia: 'Russia',
  Rwanda: 'Rwanda',
  SaintKittsAndNevis: 'Saint Kitts and Nevis',
  SaintLucia: 'Saint Lucia',
  SaintVincentAndTheGrenadines: 'Saint Vincent and the Grenadines',
  Samoa: 'Samoa',
  SanMarino: 'San Marino',
  SaoTomeAndPrincipe: 'Sao Tome and Principe',
  SaudiArabia: 'Saudi Arabia',
  Senegal: 'Senegal',
  Serbia: 'Serbia',
  Seychelles: 'Seychelles',
  SierraLeone: 'Sierra Leone',
  Singapore: 'Singapore',
  Slovakia: 'Slovakia',
  Slovenia: 'Slovenia',
  SolomonIslands: 'Solomon Islands',
  Somalia: 'Somalia',
  SouthAfrica: 'South Africa',
  Spain: 'Spain',
  SriLanka: 'Sri Lanka',
  Sudan: 'Sudan',
  SouthSudan: 'South Sudan',
  Suriname: 'Suriname',
  Sweden: 'Sweden',
  Switzerland: 'Switzerland',
  Syria: 'Syria',
  Taiwan: 'Taiwan',
  Tajikistan: 'Tajikistan',
  Tanzania: 'Tanzania',
  Thailand: 'Thailand',
  Togo: 'Togo',
  Tonga: 'Tonga',
  TrinidadAndTobago: 'Trinidad and Tobago',
  Tunisia: 'Tunisia',
  Turkey: 'Turkey',
  Turkmenistan: 'Turkmenistan',
  TurksAndCaicosIslands: 'Turks and Caicos Islands',
  Tuvalu: 'Tuvalu',
  Uganda: 'Uganda',
  Ukraine: 'Ukraine',
  UnitedArabEmirates: 'United Arab Emirates',
  UnitedKingdom: 'United Kingdom',
  UnitedStates: 'United States',
  AmericanSamoa: 'American Samoa',
  Guam: 'Guam',
  NorthernMarianaIslands: 'Northern Mariana Islands',
  PuertoRico: 'Puerto Rico',
  UnitedStatesVirginIslands: 'United States Virgin Islands',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Uzbekistan',
  Vanuatu: 'Vanuatu',
  VaticanCity: 'Vatican City',
  Venezuela: 'Venezuela',
  Vietnam: 'Vietnam',
  Yemen: 'Yemen',
  Zambia: 'Zambia',
  Zimbabwe: 'Zimbabwe',
  SouthKorea: 'South Korea',
  NorthKorea: 'North Korea',
  TimorLeste: 'Timor-Leste',
  Myanmar: 'Myanmar',
  Test: 'Test',
};
text.ru.countries = {
  Afghanistan: 'Афганистан',
  Albania: 'Албания',
  Algeria: 'Алжир',
  Andorra: 'Андорра',
  Angola: 'Ангола',
  AntiguaAndBarbuda: 'Антигуа и Барбуда',
  Argentina: 'Аргентина',
  Armenia: 'Армения',
  Aruba: 'Аруба',
  Australia: 'Австралия',
  Austria: 'Австрия',
  Azerbaijan: 'Азербайджан',
  Bahamas: 'Багамы',
  Bahrain: 'Бахрейн',
  Bangladesh: 'Бангладеш',
  Barbados: 'Барбадос',
  Belarus: 'Беларусь',
  Belgium: 'Бельгия',
  Belize: 'Белиз',
  Benin: 'Бенин',
  Bermuda: 'Бермуды',
  Bhutan: 'Бутан',
  Bolivia: 'Боливия',
  BosniaAndHerzegovina: 'Босния и Герцеговина',
  Botswana: 'Ботсвана',
  Brazil: 'Бразилия',
  BritishVirginIslands: 'Британские Виргинские острова',
  Brunei: 'Бруней',
  Bulgaria: 'Болгария',
  BurkinaFaso: 'Буркина-Фасо',
  Burundi: 'Бурунди',
  CaboVerde: 'Кабо-Верде',
  Cambodia: 'Камбоджа',
  Cameroon: 'Камерун',
  Canada: 'Канада',
  CaymanIslands: 'Каймановы острова',
  CentralAfricanRepublic: 'Центрально-Африканская Республика',
  Chad: 'Чад',
  Chile: 'Чили',
  China: 'Китай',
  Colombia: 'Колумбия',
  Comoros: 'Коморы',
  CongoBrazzaville: 'Конго-Браззавиль',
  CongoKinshasa: 'Конго-Киншаса',
  CostaRica: 'Коста-Рика',
  CoteDIvoire: 'Кот-д’Ивуар',
  Croatia: 'Хорватия',
  Cuba: 'Куба',
  Curacao: 'Кюрасао',
  Cyprus: 'Кипр',
  Czechia: 'Чехия',
  Denmark: 'Дания',
  FaroeIslands: 'Фарерские острова',
  Greenland: 'Гренландия',
  Djibouti: 'Джибути',
  Dominica: 'Доминика',
  DominicanRepublic: 'Доминиканская Республика',
  Ecuador: 'Эквадор',
  Egypt: 'Египет',
  ElSalvador: 'Сальвадор',
  EquatorialGuinea: 'Экваториальная Гвинея',
  Eritrea: 'Эритрея',
  Estonia: 'Эстония',
  Eswatini: 'Эсватини',
  Ethiopia: 'Эфиопия',
  Fiji: 'Фиджи',
  Finland: 'Финляндия',
  AlandIslands: 'Аландские острова',
  France: 'Франция',
  FrenchGuiana: 'Французская Гвиана',
  FrenchPolynesia: 'Французская Полинезия',
  Guadeloupe: 'Гваделупа',
  Martinique: 'Мартиника',
  Mayotte: 'Майотта',
  NewCaledonia: 'Новая Каледония',
  Reunion: 'Реюньон',
  SaintBarthelemy: 'Сен-Бартельми',
  SaintMartin: 'Сен-Мартен',
  SaintPierreAndMiquelon: 'Сен-Пьер и Микелон',
  WallisAndFutuna: 'Уоллис и Футуна',
  Gabon: 'Габон',
  Gambia: 'Гамбия',
  Georgia: 'Грузия',
  Germany: 'Германия',
  Ghana: 'Гана',
  Gibraltar: 'Гибралтар',
  Greece: 'Греция',
  Grenada: 'Гренада',
  Guatemala: 'Гватемала',
  Guinea: 'Гвинея',
  GuineaBissau: 'Гвинея-Бисау',
  Guyana: 'Гайана',
  Haiti: 'Гаити',
  Honduras: 'Гондурас',
  HongKong: 'Гонконг',
  Hungary: 'Венгрия',
  Iceland: 'Исландия',
  India: 'Индия',
  Indonesia: 'Индонезия',
  Iran: 'Иран',
  Iraq: 'Ирак',
  Ireland: 'Ирландия',
  Israel: 'Израиль',
  Italy: 'Италия',
  Jamaica: 'Ямайка',
  Japan: 'Япония',
  Jordan: 'Иордания',
  Kazakhstan: 'Казахстан',
  Kenya: 'Кения',
  Kiribati: 'Кирибати',
  Kosovo: 'Косово',
  Kuwait: 'Кувейт',
  Kyrgyzstan: 'Кыргызстан',
  Laos: 'Лаос',
  Latvia: 'Латвия',
  Lebanon: 'Ливан',
  Lesotho: 'Лесото',
  Liberia: 'Либерия',
  Libya: 'Ливия',
  Liechtenstein: 'Лихтенштейн',
  Lithuania: 'Литва',
  Luxembourg: 'Люксембург',
  Madagascar: 'Мадагаскар',
  Malawi: 'Малави',
  Malaysia: 'Малайзия',
  Maldives: 'Мальдивы',
  Mali: 'Мали',
  Malta: 'Мальта',
  MarshallIslands: 'Маршалловы острова',
  Mauritania: 'Мавритания',
  Mauritius: 'Маврикий',
  Mexico: 'Мексика',
  Micronesia: 'Микронезия',
  Moldova: 'Молдова',
  Monaco: 'Монако',
  Mongolia: 'Монголия',
  Montenegro: 'Черногория',
  Morocco: 'Марокко',
  Mozambique: 'Мозамбик',
  Namibia: 'Намибия',
  Nauru: 'Науру',
  Nepal: 'Непал',
  Netherlands: 'Нидерланды',
  NewZealand: 'Новая Зеландия',
  Nicaragua: 'Никарагуа',
  Niger: 'Нигер',
  Nigeria: 'Нигерия',
  NorthMacedonia: 'Северная Македония',
  Norway: 'Норвегия',
  SvalbardAndJanMayen: 'Шпицберген и Ян-Майен',
  Oman: 'Оман',
  Pakistan: 'Пакистан',
  Palau: 'Палау',
  Panama: 'Панама',
  PapuaNewGuinea: 'Папуа - Новая Гвинея',
  Paraguay: 'Парагвай',
  Peru: 'Перу',
  Philippines: 'Филиппины',
  Poland: 'Польша',
  Portugal: 'Португалия',
  Qatar: 'Катар',
  Romania: 'Румыния',
  Russia: 'Россия',
  Rwanda: 'Руанда',
  SaintKittsAndNevis: 'Сент-Китс и Невис',
  SaintLucia: 'Санкт-Люсия',
  SaintVincentAndTheGrenadines: 'Сент-Винсент и Гренадины',
  Samoa: 'Самоа',
  SanMarino: 'Сан-Марино',
  SaoTomeAndPrincipe: 'Сан-Томе и Принсипи',
  SaudiArabia: 'Саудовская Аравия',
  Senegal: 'Сенегал',
  Serbia: 'Сербия',
  Seychelles: 'Сейшелы',
  SierraLeone: 'Сьерра-Леоне',
  Singapore: 'Сингапур',
  Slovakia: 'Словакия',
  Slovenia: 'Словения',
  SolomonIslands: 'Соломоновы острова',
  Somalia: 'Сомали',
  SouthAfrica: 'Южная Африка',
  Spain: 'Испания',
  SriLanka: 'Шри-Ланка',
  Sudan: 'Судан',
  SouthSudan: 'Южный Суданn',
  Suriname: 'Суринам',
  Sweden: 'Швеция',
  Switzerland: 'Швейцария',
  Syria: 'Сирия',
  Taiwan: 'Тайвань',
  Tajikistan: 'Таджикистан',
  Tanzania: 'Танзания',
  Thailand: 'Таиланд',
  Togo: 'Того',
  Tonga: 'Тонга',
  TrinidadAndTobago: 'Тринидад и Тобаго',
  Tunisia: 'Тунис',
  Turkey: 'Турция',
  Turkmenistan: 'Туркменистан',
  TurksAndCaicosIslands: 'Теркс и Кайкос',
  Tuvalu: 'Тувалу',
  Uganda: 'Уганда',
  Ukraine: 'Украина',
  UnitedArabEmirates: 'Объединенные Арабские Эмираты',
  UnitedKingdom: 'Великобритания',
  UnitedStates: 'Соединенные Штаты',
  AmericanSamoa: 'Американское Самоа',
  Guam: 'Гуам',
  NorthernMarianaIslands: 'Северные Марианские Острова',
  PuertoRico: 'Пуэрто-Рико',
  UnitedStatesVirginIslands: 'Американские Виргинские Острова',
  Uruguay: 'Уругвай',
  Uzbekistan: 'Узбекистан',
  Vanuatu: 'Вануату',
  VaticanCity: 'Ватикан',
  Venezuela: 'Венесуэла',
  Vietnam: 'Вьетнам',
  Yemen: 'Йемен',
  Zambia: 'Замбия',
  Zimbabwe: 'Зимбабве',
  SouthKorea: 'Южная Корея',
  NorthKorea: 'Северная Корея',
  TimorLeste: 'Тимор-Лешти',
  Myanmar: 'Мьянма',
  Test: 'Тест',
},
text.lv.countries = {
  Afghanistan: 'Afganistāna',
  Albania: 'Albānija',
  Algeria: 'Alžīrija',
  Andorra: 'Andora',
  Angola: 'Angola',
  AntiguaAndBarbuda: 'Antigva un Barbuda',
  Argentina: 'Argentīna',
  Armenia: 'Armēnija',
  Aruba: 'Aruba',
  Australia: 'Austrālija',
  Austria: 'Austrija',
  Azerbaijan: 'Azerbaidžāna',
  Bahamas: 'Bahamu salas',
  Bahrain: 'Bahreina',
  Bangladesh: 'Bangladeša',
  Barbados: 'Barbadosa',
  Belarus: 'Baltkrievija',
  Belgium: 'Beļģija',
  Belize: 'Beliza',
  Benin: 'Benina',
  Bermuda: 'Bermudu salas',
  Bhutan: 'Butāna',
  Bolivia: 'Bolīvija',
  BosniaAndHerzegovina: 'Bosnija un Hercegovina',
  Botswana: 'Botsvāna',
  Brazil: 'Brazīlija',
  BritishVirginIslands: 'Britu Virdžīnas',
  Brunei: 'Bruneja',
  Bulgaria: 'Bulgārija',
  BurkinaFaso: 'Burkina Faso',
  Burundi: 'Burundija',
  CaboVerde: 'Kaboverde',
  Cambodia: 'Kambodža',
  Cameroon: 'Kamerūna',
  Canada: 'Kanāda',
  CaymanIslands: 'Kaimanu salas',
  CentralAfricanRepublic: 'Centrālāfrikas Republika',
  Chad: 'Čada',
  Chile: 'Čīle',
  China: 'Ķīna',
  Colombia: 'Kolumbija',
  Comoros: 'Komoras',
  CongoBrazzaville: 'Kongo-Brazavila',
  CongoKinshasa: 'Kongo-Kinšasa',
  CostaRica: 'Kostarika',
  CoteDIvoire: 'Kotdivuāra',
  Croatia: 'Horvātija',
  Cuba: 'Kuba',
  Curacao: 'Kirasao',
  Cyprus: 'Kipra',
  Czechia: 'Čehija',
  Denmark: 'Dānija',
  FaroeIslands: 'Fēru salas',
  Greenland: 'Grenlande',
  Djibouti: 'Džibutija',
  Dominica: 'Dominika',
  DominicanRepublic: 'Dominikānas Republika',
  Ecuador: 'Ekvadora',
  Egypt: 'Ēģipte',
  ElSalvador: 'Salvadora',
  EquatorialGuinea: 'Ekvatoriālā Gvineja',
  Eritrea: 'Eritreja',
  Estonia: 'Igaunija',
  Eswatini: 'Svatini',
  Ethiopia: 'Etiopija',
  Fiji: 'Fidži',
  Finland: 'Somija',
  AlandIslands: 'Ālandu salas',
  France: 'Francija',
  FrenchGuiana: 'Franču Gviāna',
  FrenchPolynesia: 'Franču Polinēzija',
  Guadeloupe: 'Gvadelupa',
  Martinique: 'Martinika',
  Mayotte: 'Majota',
  NewCaledonia: 'Jaunkaledonija',
  Reunion: 'Reinjona',
  SaintBarthelemy: 'Saint Barthélemy',
  SaintMartin: 'Senmartēna',
  SaintPierreAndMiquelon: 'Senpjēra un Mikelona',
  WallisAndFutuna: 'Volisa un Futuna',
  Gabon: 'Gabona',
  Gambia: 'Gambija',
  Georgia: 'Gruzija',
  Germany: 'Vācija',
  Ghana: 'Gana',
  Gibraltar: 'Gibraltārs',
  Greece: 'Grieķija',
  Grenada: 'Grenāda',
  Guatemala: 'Gvatemala',
  Guinea: 'Gvineja',
  GuineaBissau: 'Gvineja-Bisava',
  Guyana: 'Gajāna',
  Haiti: 'Haiti',
  Honduras: 'Hondurasa',
  HongKong: 'Honkonga',
  Hungary: 'Ungārija',
  Iceland: 'Islande',
  India: 'Indija',
  Indonesia: 'Indonēzija',
  Iran: 'Irāna',
  Iraq: 'Irāka',
  Ireland: 'Īrija',
  Israel: 'Izraēla',
  Italy: 'Itālija',
  Jamaica: 'Jamaika',
  Japan: 'Japāna',
  Jordan: 'Jordānija',
  Kazakhstan: 'Kazahstāna',
  Kenya: 'Kenija',
  Kiribati: 'Kiribati',
  Kosovo: 'Kosova',
  Kuwait: 'Kuveita',
  Kyrgyzstan: 'Kirgizstāna',
  Laos: 'LaoLaosas',
  Latvia: 'Latvija',
  Lebanon: 'Libāna',
  Lesotho: 'Lesoto',
  Liberia: 'Libērija',
  Libya: 'Lībija',
  Liechtenstein: 'Lihtenšteina',
  Lithuania: 'Lietuva',
  Luxembourg: 'Luksemburga',
  Madagascar: 'Madagaskara',
  Malawi: 'Malāvija',
  Malaysia: 'Malaizija',
  Maldives: 'Maldīvija',
  Mali: 'Mali',
  Malta: 'Malta',
  MarshallIslands: 'Māršala Salas',
  Mauritania: 'Mauritānija',
  Mauritius: 'Maurīcija',
  Mexico: 'Meksika',
  Micronesia: 'Mikronēzija',
  Moldova: 'Moldova',
  Monaco: 'Monako',
  Mongolia: 'Mongolija',
  Montenegro: 'Melnkalne',
  Morocco: 'Maroka',
  Mozambique: 'Mozambika',
  Namibia: 'Namībija',
  Nauru: 'Nauru',
  Nepal: 'Nepāla',
  Netherlands: 'Nīderlande',
  NewZealand: 'Jaunzēlande',
  Nicaragua: 'Nikaragva',
  Niger: 'Nigēra',
  Nigeria: 'Nigērija',
  NorthMacedonia: 'Ziemeļmaķedonija',
  Norway: 'Norvēģija',
  SvalbardAndJanMayen: 'Svalbard and Jan Mayen',
  Oman: 'Omāna',
  Pakistan: 'Pakistāna',
  Palau: 'Palau',
  Panama: 'Panama',
  PapuaNewGuinea: 'Papua-Jaungvineja',
  Paraguay: 'Paragvaja',
  Peru: 'Peru',
  Philippines: 'Filipīnas',
  Poland: 'Polija',
  Portugal: 'Portugāle',
  Qatar: 'Katara',
  Romania: 'Rumānija',
  Russia: 'Krievija',
  Rwanda: 'Ruanda',
  SaintKittsAndNevis: 'Sentkitsa un Nevisa',
  SaintLucia: 'Sentlūsija',
  SaintVincentAndTheGrenadines: 'Sentvinsenta un Grenadīnas',
  Samoa: 'Samoa',
  SanMarino: 'Sanmarīno',
  SaoTomeAndPrincipe: 'Santome un Prinsipi',
  SaudiArabia: 'Saūda Arābija',
  Senegal: 'Senegāla',
  Serbia: 'Serbija',
  Seychelles: 'Seišelas',
  SierraLeone: 'Sjerraleone',
  Singapore: 'Singapūra',
  Slovakia: 'Slovākija',
  Slovenia: 'Slovēnija',
  SolomonIslands: 'Zālamana salas',
  Somalia: 'Somālija',
  SouthAfrica: 'Dienvidāfrika',
  Spain: 'Spānija',
  SriLanka: 'Šrilanka',
  Sudan: 'Sudāna',
  SouthSudan: 'Dienvidsudāna',
  Suriname: 'Surinama',
  Sweden: 'Zviedrija',
  Switzerland: 'Šveice',
  Syria: 'Sīrija',
  Taiwan: 'Taivānā',
  Tajikistan: 'Tadžikistāna',
  Tanzania: 'Tanzānija',
  Thailand: 'Taizeme',
  Togo: 'Togo',
  Tonga: 'Tonga',
  TrinidadAndTobago: 'Trinidāda un Tobāgo',
  Tunisia: 'Tunisa',
  Turkey: 'Turcija',
  Turkmenistan: 'Turkmenistāna',
  TurksAndCaicosIslands: 'Tērksas un Kaikosas',
  Tuvalu: 'Tuvalu',
  Uganda: 'Uganda',
  Ukraine: 'Ukraina',
  UnitedArabEmirates: 'Apvienotie Arābu Emirāti',
  UnitedKingdom: 'Apvienotā Karaliste',
  UnitedStates: 'Amerikas Savienotās Valstis',
  AmericanSamoa: 'ASV Samoa',
  Guam: 'Guama',
  NorthernMarianaIslands: 'Northern Mariana Islands',
  PuertoRico: 'Puertoriko',
  UnitedStatesVirginIslands: 'ASV Virdžīnas',
  Uruguay: 'Urugvaja',
  Uzbekistan: 'Uzbekistāna',
  Vanuatu: 'Vanuatu',
  VaticanCity: 'Vatikāns',
  Venezuela: 'Venecuēla',
  Vietnam: 'Vjetnama',
  Yemen: 'Jemena',
  Zambia: 'Zambija',
  Zimbabwe: 'Zimbabve',
  SouthKorea: 'Dienvidkoreja',
  NorthKorea: 'Ziemeļkoreja',
  TimorLeste: 'Austrumtimora',
  Myanmar: 'Mjanma',
  Test: 'Tests',
};

// Languages
export const languages = {
  en: 'English',
  enTranslated: 'English',
  ru: 'Russian',
  ruTranslated: 'Русский',
  lv: 'Latvian',
  lvTranslated: 'Latviešu',
};

export const availableCurrencies = [
  '€',
  '$',
  'zł',
  '£',
  '₽',
  'Afs',
  'Lek',
  'DA',
  'Kz',
  '֏',
  'դր.',
  'ƒ',
  '₼',
  'BD',
  '৳',
  'Rbls',
  'Fr',
  'Nu',
  '₹',
  'Bs',
  'KM',
  'P',
  'R$',
  'Lev',
  'CR',
  '₿',
  '¥',
  '₡',
  'Kč',
  'kr',
  'LE',
  'Nkf',
  'E',
  'R',
  'Br',
  'D',
  '₾',
  '₵',
  'Q',
  'G',
  'L',
  'Ft',
  'Rp',
  'Rls',
  'ID',
  '₪',
  'JD',
  '₸',
  'Shs',
  '₩',
  'KD',
  'som',
  '₭',
  'LL',
  'M',
  'LD',
  'MOP$',
  'K',
  'RM',
  'Rf',
  'UM',
  'Rs',
  'Lei',
  'DH',
  'Mt',
  'Ks',
  'C$',
  '₦',
  'DEN',
  '₺',
  'RO',
  'B/',
  '₲',
  'S/',
  '₱',
  'QR',
  'Pts',
  'Db',
  'DIN',
  'Le',
  'SSP',
  'LS',
  '฿',
  'T$',
  'р',
  'DT',
  '₴',
  'Dhs',
  'soum',
  'VT',
  'Bs.S',
  '₫',
];

// Setting available localizations
const a = [];
for (const [key] of Object.entries(text)) {
  a.push(key);
}
export const availableLocalizations = a;

// Setting available countries
const b = [];
for (const [key] of Object.entries(text.en.countries)) {
  b.push(key);
}
export const availableCountries = b;

const getLocalizedText = appLanguage => {
  return text[appLanguage];
};

export default getLocalizedText;